import type { Metadata } from "next";
import { Arsenal } from "next/font/google";
import "./globals.css";

import { Noto_Sans_JP } from "next/font/google";

const NotoSans = Noto_Sans_JP({
  subsets: ["latin-ext"],
  weight: "400",
  variable: "--font-noto",
});


// 見出し用の Google フォント Arsenal
const arsenal = Arsenal({
  variable: "--font-arsenal",
  subsets: ["latin"], //言語設定
  weight: ["400", "700"],
});

// ページ全体のメタ情報を定義する
// title や description はSEOやブラウザの表示に使われる
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${NotoSans.variable} 
        ${arsenal.variable}`}
    >
      <body className="text-neutral-800 leading-loose font-normal font-sans antialiased tracking-wider text-base">{children}</body>
    </html>
  );
}
