import type { Metadata } from "next";
import { Roboto, Arsenal } from "next/font/google";
import "./globals.css";

// 本文用の Google フォント Roboto
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// 見出し用の Google フォント Arsenal
const arsenal = Arsenal({
  variable: "--font-arsenal",
  subsets: ["latin"], //言語設定
  weight: ["400", "700"],
});

// ページ全体のメタ情報を定義する
// title や description はSEOやブラウザの表示に使われる
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${roboto.variable} 
        ${arsenal.variable}`}
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}
